#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_2_file=$1
server_ip=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username"@"$server_ip":~/
