#!/usr/bin/env bash
# install load balancer
# Install and configure HAproxy on your lb-01 server.Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend deetechwiz
	bind *:80
	mode http
	default_backend app

backend app
   balance roundrobin
   server 335310-web-01 100.25.192.119:80 check
   server 335310-web-02	54.148.84.198:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
