#!/usr/bin/env bash
# Nginx likes port 80

sudo apt-get update -y
sudo apt-get install -y nginx
rm /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-available/default
sudo service nginx restart
