#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely.
# Requirements:
# In between each iteration of the loop, add a sleep 2

while [ 0 -eq 0 ]; do
	echo "To infinity and beyond"
	sleep 2
done
