#!/usr/bin/env bash
#a Bash script that gives you information about the school file.
#Requirements:
#You must use if and, else (case is forbidden)
# Your Bash script should check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

if [ -e "school" ]; then
	echo "school file exist"
	if [ ! -s "school" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "school" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
