#!/usr/bin/env bash
#a Bash script that gives you information about the school file.
#Requirements:
#You must use if and, else (case is forbidden)
# Your Bash script should check if the file exists and print:
# if the file exists: school file exists
i="school"
if [ -e "$i" ]; then
	echo "school file exist"
	if [ -s "$i" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$i" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
